# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven CI with TestNG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 'corretto11'  # Specify the desired Corretto version, e.g., 'corretto11'

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Update this to use Node 16

      - name: Build the Maven project
        run: mvn clean install

      - name: Run TestNG tests
        run: mvn test -DsuiteXmlFile=testng.xml
